
--CREATE LOGINS WITH PASSWORDS

USE master;

CREATE LOGIN THULANI_Login     WITH PASSWORD = 'Thulani@123';
CREATE LOGIN KHWATHISEDZO_Login WITH PASSWORD = 'Khwa@123';
CREATE LOGIN PHUTI_Login       WITH PASSWORD = 'Phuti@123';
CREATE LOGIN BOHLALE_Login     WITH PASSWORD = 'Bohla@123';
CREATE LOGIN ARNOLD_Login      WITH PASSWORD = 'Arnold@123';
CREATE LOGIN THEMBA_Login      WITH PASSWORD = 'Themba@123';
CREATE LOGIN LUCIA_Login       WITH PASSWORD = 'Lucia@123';
CREATE LOGIN MABATHO_Login     WITH PASSWORD = 'Mabatho@123';
CREATE LOGIN KAMOGELO_Login    WITH PASSWORD = 'Kamogelo@123';
CREATE LOGIN MASETE_Login      WITH PASSWORD = 'Masete@123';
CREATE LOGIN FORTUNE_Login     WITH PASSWORD = 'Fortune@123';
CREATE LOGIN MAQUEW_Login      WITH PASSWORD = 'Maquew@123';

/*
his section enables all SQL Server logins to ensure that each user account is active and able to authenticate and connect to the server. 

USE master;
GO

ALTER LOGIN THULANI_Login     ENABLE;
ALTER LOGIN KHWATHISEDZO_Login ENABLE;
ALTER LOGIN PHUTI_Login       ENABLE;
ALTER LOGIN BOHLALE_Login     ENABLE;
ALTER LOGIN ARNOLD_Login      ENABLE;
ALTER LOGIN THEMBA_Login      ENABLE;
ALTER LOGIN LUCIA_Login       ENABLE;
ALTER LOGIN MABATHO_Login     ENABLE;
ALTER LOGIN KAMOGELO_Login    ENABLE;
ALTER LOGIN MASETE_Login      ENABLE;
ALTER LOGIN FORTUNE_Login     ENABLE;
ALTER LOGIN MAQUEW_Login      ENABLE;
GO;

*/

USE AdventureWorks2022;


-- CREATE ROLES
CREATE ROLE SalesRole;
CREATE ROLE HRRole;
CREATE ROLE DBA_Role;



-- SalesRole
GRANT SELECT, INSERT, UPDATE 
ON Sales.SalesOrderHeader TO SalesRole;

GRANT SELECT, INSERT, UPDATE 
ON Sales.SalesOrderDetail TO SalesRole;

DENY SELECT 
ON HumanResources.Employee TO SalesRole;


-- HRRole
GRANT SELECT 
ON HumanResources.Employee TO HRRole;

DENY SELECT 
ON Sales.SalesOrderHeader TO HRRole;

DENY SELECT 
ON Sales.SalesOrderDetail TO HRRole;


-- DBA_Role
GRANT CONTROL 
ON DATABASE::AdventureWorks2022 TO DBA_Role;


--CREATE USERS LINKED TO LOGINS
CREATE USER THULANI     FOR LOGIN THULANI_Login;
CREATE USER KHWATHISEDZO FOR LOGIN KHWATHISEDZO_Login;
CREATE USER PHUTI       FOR LOGIN PHUTI_Login;
CREATE USER BOHLALE     FOR LOGIN BOHLALE_Login;
CREATE USER ARNOLD      FOR LOGIN ARNOLD_Login;
CREATE USER THEMBA      FOR LOGIN THEMBA_Login;
CREATE USER LUCIA       FOR LOGIN LUCIA_Login;
CREATE USER MABATHO     FOR LOGIN MABATHO_Login;
CREATE USER KAMOGELO    FOR LOGIN KAMOGELO_Login;
CREATE USER MASETE      FOR LOGIN MASETE_Login;
CREATE USER FORTUNE     FOR LOGIN FORTUNE_Login;
CREATE USER MAQUEW      FOR LOGIN MAQUEW_Login;


-- ASSIGN USERS TO ROLES

-- SalesRole users
ALTER ROLE SalesRole ADD MEMBER THULANI;
ALTER ROLE SalesRole ADD MEMBER KHWATHISEDZO;
ALTER ROLE SalesRole ADD MEMBER PHUTI;
ALTER ROLE SalesRole ADD MEMBER BOHLALE;

-- HRRole users
ALTER ROLE HRRole ADD MEMBER ARNOLD;
ALTER ROLE HRRole ADD MEMBER THEMBA;
ALTER ROLE HRRole ADD MEMBER LUCIA;
ALTER ROLE HRRole ADD MEMBER MABATHO;

-- DBA_Role users
ALTER ROLE DBA_Role ADD MEMBER KAMOGELO;
ALTER ROLE DBA_Role ADD MEMBER MASETE;
ALTER ROLE DBA_Role ADD MEMBER FORTUNE;
ALTER ROLE DBA_Role ADD MEMBER MAQUEW;

--testing

EXECUTE AS USER = 'THULANI';
-- Should work
SELECT * FROM Sales.SalesOrderHeader;

-- Should FAIL
SELECT * FROM HumanResources.Employee;

REVERT;


/* This section uses ALTER USER because the database users already exist, instead of creating them again which causes errors,
it re links each existing user to its corresponding login to fix orphaned user issues and ensure proper access and permissions.*/
USE AdventureWorks2022;
GO

ALTER USER THULANI     WITH LOGIN = THULANI_Login;
ALTER USER KHWATHISEDZO WITH LOGIN = KHWATHISEDZO_Login;
ALTER USER PHUTI       WITH LOGIN = PHUTI_Login;
ALTER USER BOHLALE     WITH LOGIN = BOHLALE_Login;
ALTER USER ARNOLD      WITH LOGIN = ARNOLD_Login;
ALTER USER THEMBA      WITH LOGIN = THEMBA_Login;
ALTER USER LUCIA       WITH LOGIN = LUCIA_Login;
ALTER USER MABATHO     WITH LOGIN = MABATHO_Login;
ALTER USER KAMOGELO    WITH LOGIN = KAMOGELO_Login;
ALTER USER MASETE      WITH LOGIN = MASETE_Login;
ALTER USER FORTUNE     WITH LOGIN = FORTUNE_Login;
ALTER USER MAQUEW      WITH LOGIN = MAQUEW_Login;
GO